<!-- begin inputs_fields/search_inputs_fields.tpl -->

<TMPL_IF NAME=EQUIFAX_RECOVERY_SEARCH><TMPL_INCLUDE NAME="inputs_fields/equifax_recovery_search.tpl"></TMPL_IF>
<TMPL_IF NAME=EQUIFAX_CREDIT_SEARCH><TMPL_INCLUDE NAME="inputs_fields/equifax_credit_search.tpl"></TMPL_IF>
<TMPL_IF NAME=RISKVIEW_SEARCH><TMPL_INCLUDE NAME="inputs_fields/riskview_search.tpl"></TMPL_IF>
<TMPL_IF NAME=BUS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/bus_search.tpl"></TMPL_IF>
<TMPL_IF NAME=BUS_CREDIT_SEARCH><TMPL_INCLUDE NAME="inputs_fields/bus_credit_search.tpl"></TMPL_IF>
<TMPL_IF NAME=CORPORATION_SEARCH><TMPL_INCLUDE NAME="inputs_fields/corporation_search.tpl"></TMPL_IF>
<TMPL_IF NAME=UCC_SEARCH><TMPL_INCLUDE NAME="inputs_fields/ucc_search.tpl"></TMPL_IF>
<TMPL_IF NAME=WHOIS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/whois_search.tpl"></TMPL_IF>
<TMPL_IF NAME=D_AND_B_SEARCH><TMPL_INCLUDE NAME="inputs_fields/d_and_b_search.tpl"></TMPL_IF>
<TMPL_IF NAME=DELCO_SEARCH><TMPL_INCLUDE NAME="inputs_fields/delco_search.tpl"></TMPL_IF>
<TMPL_IF NAME=BUS_NEWS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/bus_news_search.tpl"></TMPL_IF>
<TMPL_IF NAME=SEC_SEARCH><TMPL_INCLUDE NAME="inputs_fields/sec_search.tpl"></TMPL_IF>
<TMPL_IF NAME=EXPERIAN_SEARCH><TMPL_INCLUDE NAME="inputs_fields/experian_search.tpl"></TMPL_IF>
<TMPL_IF NAME=TRADEMARK_SEARCH><TMPL_INCLUDE NAME="inputs_fields/trademark_search.tpl"></TMPL_IF>
<TMPL_IF NAME=FICTIOUS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/fictious_search.tpl"></TMPL_IF>
<TMPL_IF NAME=AIRCRAFT_SEARCH><TMPL_INCLUDE NAME="inputs_fields/aircraft_search.tpl"></TMPL_IF>
<TMPL_IF NAME=PROPERTY_SEARCH><TMPL_INCLUDE NAME="inputs_fields/property_search.tpl"></TMPL_IF>
<TMPL_IF NAME=PROPERTY_DEED_SEARCH><TMPL_INCLUDE NAME="inputs_fields/property_deed_search.tpl"></TMPL_IF>
<TMPL_IF NAME=AVM_SEARCH><TMPL_INCLUDE NAME="inputs_fields/avm_property_search.tpl"></TMPL_IF>
<TMPL_IF NAME=MERCHANT_VESSEL_SEARCH><TMPL_INCLUDE NAME="inputs_fields/merchant_vessel_search.tpl"></TMPL_IF>
<TMPL_IF NAME=LICENSE_SEARCH><TMPL_INCLUDE NAME="inputs_fields/license_search.tpl"></TMPL_IF>
<TMPL_IF NAME=PROF_LICENSE_SEARCH><TMPL_INCLUDE NAME="inputs_fields/prof_license_search.tpl"></TMPL_IF>
<TMPL_IF NAME=DL_REG_SEARCH><TMPL_INCLUDE NAME="inputs_fields/dl_reg_search.tpl"></TMPL_IF>
<TMPL_IF NAME=FAA_PILOT_SEARCH><TMPL_INCLUDE NAME="inputs_fields/faa_pilot_search.tpl"></TMPL_IF>
<TMPL_IF NAME=LIEN_SEARCH><TMPL_INCLUDE NAME="inputs_fields/lien_search.tpl"></TMPL_IF>
<TMPL_IF NAME=BANKRUPTCY_SEARCH><TMPL_INCLUDE NAME="inputs_fields/bankruptcy_search.tpl"></TMPL_IF>
<TMPL_IF NAME=SEXPREDATOR_SEARCH><TMPL_INCLUDE NAME="inputs_fields/sexpredator_search.tpl"></TMPL_IF>
<TMPL_IF NAME=OFFICIAL_RECORDS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/official_records_search.tpl"></TMPL_IF>
<TMPL_IF NAME=MARRIAGE_SEARCH><TMPL_INCLUDE NAME="inputs_fields/marriage_search.tpl"></TMPL_IF>
<TMPL_IF NAME=FORECLOSURE_SEARCH><TMPL_INCLUDE NAME="inputs_fields/foreclosure_search.tpl"></TMPL_IF>
<TMPL_IF NAME=DEA_SEARCH><TMPL_INCLUDE NAME="inputs_fields/dea_search.tpl"></TMPL_IF>
<TMPL_IF NAME=ACCIDENT_SEARCH><TMPL_INCLUDE NAME="inputs_fields/accident_search.tpl"></TMPL_IF>
<TMPL_IF NAME=MVR_REPORT><TMPL_INCLUDE NAME="inputs_fields/mvr_report.tpl"></TMPL_IF>
<TMPL_IF NAME=CRIM_SEARCH><TMPL_INCLUDE NAME="inputs_fields/crim_search.tpl"></TMPL_IF>
<TMPL_IF NAME=PATRIOTACT_SEARCH><TMPL_INCLUDE NAME="inputs_fields/patriotact_search.tpl"></TMPL_IF>
<TMPL_IF NAME=CIVIL_COURT_SEARCH><TMPL_INCLUDE NAME="inputs_fields/civil_court_search.tpl"></TMPL_IF>
<TMPL_IF NAME=HUNTING_LICENSE_SEARCH><TMPL_INCLUDE NAME="inputs_fields/hunting_license_search.tpl"></TMPL_IF>
<TMPL_IF NAME=CONCEALED_WEAPON_SEARCH><TMPL_INCLUDE NAME="inputs_fields/concealed_weapon_search.tpl"></TMPL_IF>
<TMPL_IF NAME=VOTER_REGISTRATION_SEARCH><TMPL_INCLUDE NAME="inputs_fields/voter_registration_search.tpl"></TMPL_IF>
<TMPL_IF NAME=FIREARMS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/firearms_search.tpl"></TMPL_IF>
<TMPL_IF NAME=PERSON_SEARCH><TMPL_INCLUDE NAME="inputs_fields/person_search.tpl"></TMPL_IF>
<TMPL_IF NAME=PAW_SEARCH><TMPL_INCLUDE NAME="inputs_fields/paw_search.tpl"></TMPL_IF>
<TMPL_IF NAME=INSTANT_ID_REPORT><TMPL_INCLUDE NAME="inputs_fields/instant_id_report.tpl"></TMPL_IF>
<TMPL_IF NAME=SHOW_INTL_INSTANTID><TMPL_INCLUDE NAME="inputs_fields/intl_instantid_search.tpl"></TMPL_IF>
<TMPL_IF NAME=BUS_INSTANT_ID_REPORT><TMPL_INCLUDE NAME="inputs_fields/bus_instant_id_report.tpl"></TMPL_IF>
<TMPL_IF NAME=RATE_EVASION_REPORT><TMPL_INCLUDE NAME="inputs_fields/rate_evasion_report.tpl"></TMPL_IF>
<TMPL_IF NAME=NEWS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/news_search.tpl"></TMPL_IF>
<TMPL_IF NAME=ADV_SEARCH><TMPL_INCLUDE NAME="inputs_fields/adv_search.tpl"></TMPL_IF>
<TMPL_IF NAME=REAL_TIME_PERSON_SEARCH><TMPL_INCLUDE NAME="inputs_fields/real_time_person_search.tpl"></TMPL_IF>
<TMPL_IF NAME=DA_BASIC_SEARCH><TMPL_INCLUDE NAME="inputs_fields/da_basic_search.tpl"></TMPL_IF>
<TMPL_IF NAME=DA_REVERSE_SEARCH><TMPL_INCLUDE NAME="inputs_fields/da_reverse_search.tpl"></TMPL_IF>
<TMPL_IF NAME=DA_WIRELESS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/da_wireless_search.tpl"></TMPL_IF>
<TMPL_IF NAME=LOCATE_PLUS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/locate_plus_search.tpl"></TMPL_IF>
<TMPL_IF NAME=TODAYS_NEWS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/todays_news_search.tpl"></TMPL_IF>
<TMPL_IF NAME=US_NEWS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/us_news_search.tpl"></TMPL_IF>
<TMPL_IF NAME=NON_US_NEWS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/us_news_search.tpl"></TMPL_IF>
<TMPL_IF NAME=ARCHIVED_NEWS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/us_news_search.tpl"></TMPL_IF>
<TMPL_IF NAME=FED_CIVIL_COURT_SEARCH><TMPL_INCLUDE NAME="inputs_fields/fed_civil_court_search.tpl"></TMPL_IF>
<TMPL_IF NAME=FED_CRIM_COURT_SEARCH><TMPL_INCLUDE NAME="inputs_fields/fed_civil_court_search.tpl"></TMPL_IF>
<TMPL_IF NAME=PSPR_SEARCH><TMPL_INCLUDE NAME="inputs_fields/pspr_search.tpl"></TMPL_IF>
<TMPL_IF NAME=DO_NEWS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/do_news_search.tpl"></TMPL_IF>
<TMPL_IF NAME=OSHA_SEARCH><TMPL_INCLUDE NAME="inputs_fields/osha_search.tpl"></TMPL_IF>
<TMPL_IF NAME=DBGLOBAL_SEARCH><TMPL_INCLUDE NAME="inputs_fields/dbglobal_search.tpl"></TMPL_IF>
<TMPL_IF NAME=INSTOPICS_NEWS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/instopic_news_search.tpl"></TMPL_IF>
<TMPL_IF NAME=MP_PROVIDERS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/mp_providers_search.tpl"></TMPL_IF>
<TMPL_IF NAME=MP_SPECIALITIES_SEARCH><TMPL_INCLUDE NAME="inputs_fields/mp_specialities_search.tpl"></TMPL_IF>
<TMPL_IF NAME=MP_HOSPITALS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/mp_hospitals_search.tpl"></TMPL_IF>
<TMPL_IF NAME=COURT_CASE_SEARCH><TMPL_INCLUDE NAME="inputs_fields/court_case_search_by_type_search.tpl"></TMPL_IF>
<TMPL_IF NAME=PROVIDER_SEARCH><TMPL_INCLUDE NAME="inputs_fields/provider_search.tpl"></TMPL_IF>
<TMPL_IF NAME=SANCTION_SEARCH><TMPL_INCLUDE NAME="inputs_fields/sanction_search.tpl"></TMPL_IF>
<TMPL_IF NAME=CARFAX_REPORT><TMPL_INCLUDE NAME="inputs_fields/carfax_report.tpl"></TMPL_IF>
<TMPL_IF NAME=DEATH_SEARCH><TMPL_INCLUDE NAME="inputs_fields/death_search.tpl"></TMPL_IF>
<TMPL_IF NAME=CANADIAN_PHONES_SEARCH><TMPL_INCLUDE NAME="inputs_fields/canadian_phones_search.tpl"></TMPL_IF>
<TMPL_IF NAME=PRUDENTIAL_REPORT><TMPL_INCLUDE NAME="inputs_fields/prudential_report.tpl"></TMPL_IF>
<TMPL_IF NAME=EMAIL_SEARCH><TMPL_INCLUDE NAME="inputs_fields/email_search.tpl"></TMPL_IF>
<TMPL_IF NAME=RT_MVR_SEARCH><TMPL_INCLUDE NAME="inputs_fields/rt_mvr_search.tpl"></TMPL_IF>
<TMPL_IF NAME=CLAIMS_DISCOVERY_REPORT><TMPL_INCLUDE NAME="inputs_fields/claims_discovery_report.tpl"></TMPL_IF>
<TMPL_IF NAME=RT_PHONE_SEARCH><TMPL_INCLUDE NAME="inputs_fields/rt_phone_search.tpl"></TMPL_IF>
<TMPL_IF NAME=CARRIER_DISCOVERY_REPORT><TMPL_INCLUDE NAME="inputs_fields/carrier_discovery_report.tpl"></TMPL_IF>
<TMPL_IF NAME=BUS_QUALIFIER_REPORT><TMPL_INCLUDE NAME="inputs_fields/bus_qualifier_report.tpl"></TMPL_IF>
<TMPL_IF NAME=IND_QUALIFIER_REPORT><TMPL_INCLUDE NAME="inputs_fields/ind_qualifier_report.tpl"></TMPL_IF>
<TMPL_IF NAME=MV_WILDCARD_SEARCH><TMPL_INCLUDE NAME="inputs_fields/mv_wildcard_search.tpl"></TMPL_IF>
<TMPL_IF NAME=NPI_SEARCH><TMPL_INCLUDE NAME="inputs_fields/npi_data_search.tpl"></TMPL_IF>
<TMPL_IF NAME=CLIA_SEARCH><TMPL_INCLUDE NAME="inputs_fields/clia_search.tpl"></TMPL_IF>
<TMPL_IF NAME=NCPDP_SEARCH><TMPL_INCLUDE NAME="inputs_fields/ncpdp_search.tpl"></TMPL_IF>
<!-- end inputs_fields/search_inputs_fields.tpl -->
