<TMPL_IF GROUP_REPORT>Group Detail Report - <TMPL_VAR GROUPNAME></TMPL_IF><TMPL_IF USER_REPORT>User Detail Report - <TMPL_VAR LOGINID></TMPL_IF>
Date Range: <TMPL_VAR DATE_BEGIN> - <TMPL_VAR DATE_END>
Note: The search results listed may not match your invoice
Detailed Report:
<TMPL_UNLESS ERROR_MSG>
Ref Id,Group,<TMPL_IF GROUP_REPORT>Userid,</TMPL_IF>Date/Time,Search Terms,Form Searched
<TMPL_LOOP RESULT_LOOP><TMPL_VAR NAME=REF_ID>,<TMPL_VAR NAME=GROUP_NAME>,<TMPL_IF GROUP><TMPL_VAR NAME=USERID>,</TMPL_IF><TMPL_VAR NAME=DATE>,<TMPL_VAR NAME=SEARCH_TERMS>,<TMPL_VAR NAME=FUNCTION_NAME>
<TMPL_IF ODD></TMPL_IF></TMPL_LOOP>
Total Searches:  <TMPL_VAR TOTAL_SEARCHES> 
<TMPL_ELSE>
<TMPL_VAR ERROR_MSG>
</TMPL_UNLESS>
