Group Summary Report - <TMPL_VAR GROUPNAME>
Date Range: <TMPL_VAR DATE_BEGIN> - <TMPL_VAR DATE_END>
Note: The search results listed may not match your invoice
<TMPL_UNLESS ERROR_MSG>
Number of searches By Search Type:
<TMPL_LOOP SEARCH_TYPE>"<TMPL_VAR NAME=FUNCTION_NAME>",<TMPL_VAR NAME=TYPE_COUNT><TMPL_IF ODD></TMPL_IF>
</TMPL_LOOP>
Total:,<TMPL_VAR SEARCH_TYPE_TOTAL>

Number of searches By Reference ID:
<TMPL_LOOP REFERENCE_CODE>"<TMPL_VAR NAME=FUNCTION_NAME>",<TMPL_VAR NAME=TYPE_COUNT><TMPL_IF ODD></TMPL_IF>
</TMPL_LOOP>
Total:,<TMPL_VAR REFERENCE_CODE_TOTAL>

Daily Average of searches By Search Type:
<TMPL_LOOP SEARCH_TYPE_AVG>"<TMPL_VAR NAME=FUNCTION_NAME>",<TMPL_VAR NAME=TYPE_COUNT><TMPL_IF ODD></TMPL_IF>
</TMPL_LOOP>
Daily Average of searches By Reference ID:
<TMPL_LOOP REFERENCE_CODE_AVG>"<TMPL_VAR NAME=FUNCTION_NAME>",<TMPL_VAR NAME=TYPE_COUNT><TMPL_IF ODD></TMPL_IF>
</TMPL_LOOP>
<TMPL_ELSE>
<TMPL_VAR ERROR_MSG>
</TMPL_UNLESS>
