Management Group Report
<TMPL_UNLESS ERROR_MSG>
BillGroup: <TMPL_VAR BILLGROUP>
<TMPL_LOOP RESULT_LOOP>
Group Name: <TMPL_VAR GROUP_NAME>
User Name,User ID
<TMPL_LOOP GROUP_USERS>"<TMPL_VAR USERNAME>",<TMPL_VAR USERID><TMPL_IF ODD></TMPL_IF>
</TMPL_LOOP>
</TMPL_LOOP>
</TMPL_UNLESS>
