Management Feature Report
<TMPL_UNLESS ERROR_MSG>
BillGroup(s):<TMPL_LOOP BILLGROUPLOOP>
<TMPL_VAR BILLGROUP>
</TMPL_LOOP>
<TMPL_LOOP GROUP_HEADINGS>,<TMPL_VAR NAME>(<TMPL_VAR COUNT> users)<TMPL_VAR BILLGROUP></TMPL_LOOP>
<TMPL_LOOP RESULT_LOOP>
"<TMPL_VAR SEARCH_NAME>",<TMPL_LOOP SEARCH_ENABLED><TMPL_IF ENABLED>X,<TMPL_ELSE>" ",</TMPL_IF></TMPL_LOOP><TMPL_IF ODD></TMPL_IF></TMPL_LOOP>
</TMPL_UNLESS>
