<INPUT type=hidden NAME="SESSION_ID" VALUE="<TMPL_VAR NAME=SESSION_ID>">
<INPUT type=hidden NAME="CSRF_TOKEN" VALUE="<TMPL_VAR NAME=CSRF_TOKEN>">  
<INPUT type=hidden NAME="SKIN_TYPE" VALUE="<TMPL_VAR NAME=SKIN_TYPE>">
<INPUT type=hidden NAME="APPLICATION_TYPE" VALUE="<TMPL_VAR NAME=APPLICATION_TYPE>">
<INPUT type=hidden NAME="EVENT" VALUE="">
<INPUT type=hidden NAME="ACTIVE_COMPANY_ID" VALUE="<TMPL_VAR NAME=ACTIVE_COMPANY_ID>">
<INPUT type=hidden NAME="ACTIVE_COMPANY_TYPE" VALUE="<TMPL_VAR NAME=ACTIVE_COMPANY_TYPE>">
<INPUT type=hidden NAME="IS_ADMIN_REPORTING" VALUE="<TMPL_VAR NAME=IS_ADMIN_REPORTING>">
<INPUT type=hidden NAME="SELECTED_BILLGROUP" VALUE="<TMPL_IF NAME=SELECTED_BILLGROUP><TMPL_VAR NAME=SELECTED_BILLGROUP><TMPL_ELSE>0</TMPL_IF>">
