<!-- begin inputs_fields/search_inputs_fields.tpl -->

<TMPL_IF NAME=EQUIFAX_RECOVERY_SEARCH><TMPL_INCLUDE NAME="inputs_fields/equifax_recovery_search.tpl"></TMPL_IF>
<TMPL_IF NAME=EQUIFAX_CREDIT_SEARCH><TMPL_INCLUDE NAME="inputs_fields/equifax_credit_search.tpl"></TMPL_IF>
<TMPL_IF NAME=RISKVIEW_SEARCH><TMPL_INCLUDE NAME="inputs_fields/riskview_search.tpl"></TMPL_IF>
<TMPL_IF NAME=BUS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/bus_search.tpl"></TMPL_IF>
<TMPL_IF NAME=BUS_CREDIT_SEARCH><TMPL_INCLUDE NAME="inputs_fields/bus_credit_search.tpl"></TMPL_IF>
<TMPL_IF NAME=CORPORATION_SEARCH><TMPL_INCLUDE NAME="inputs_fields/corporation_search.tpl"></TMPL_IF>
<TMPL_IF NAME=UCC_SEARCH><TMPL_INCLUDE NAME="inputs_fields/ucc_search.tpl"></TMPL_IF>
<TMPL_IF NAME=WHOIS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/whois_search.tpl"></TMPL_IF>
<TMPL_IF NAME=D_AND_B_SEARCH><TMPL_INCLUDE NAME="inputs_fields/d_and_b_search.tpl"></TMPL_IF>
<TMPL_IF NAME=DELCO_SEARCH><TMPL_INCLUDE NAME="inputs_fields/delco_search.tpl"></TMPL_IF>
<TMPL_IF NAME=BUS_NEWS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/bus_news_search.tpl"></TMPL_IF>
<TMPL_IF NAME=SEC_SEARCH><TMPL_INCLUDE NAME="inputs_fields/sec_search.tpl"></TMPL_IF>
<TMPL_IF NAME=EXPERIAN_SEARCH><TMPL_INCLUDE NAME="inputs_fields/experian_search.tpl"></TMPL_IF>
<TMPL_IF NAME=TRADEMARK_SEARCH><TMPL_INCLUDE NAME="inputs_fields/trademark_search.tpl"></TMPL_IF>
<TMPL_IF NAME=FICTIOUS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/fictious_search.tpl"></TMPL_IF>
<TMPL_IF NAME=AIRCRAFT_SEARCH><TMPL_INCLUDE NAME="inputs_fields/aircraft_search.tpl"></TMPL_IF>
<TMPL_IF NAME=FCRA_AIRCRAFT_SEARCH><TMPL_INCLUDE NAME="inputs_fields/fcra_search.tpl"></TMPL_IF>
<TMPL_IF NAME=PROPERTY_SEARCH><TMPL_INCLUDE NAME="inputs_fields/property_search.tpl"></TMPL_IF>
<TMPL_IF NAME=PROPERTY_DEED_SEARCH><TMPL_INCLUDE NAME="inputs_fields/property_deed_search.tpl"></TMPL_IF>
<TMPL_IF NAME=AVM_SEARCH><TMPL_INCLUDE NAME="inputs_fields/avm_property_search.tpl"></TMPL_IF>
<TMPL_IF NAME=MERCHANT_VESSEL_SEARCH><TMPL_INCLUDE NAME="inputs_fields/merchant_vessel_search.tpl"></TMPL_IF>
<TMPL_IF NAME=FCRA_MERCHANT_VESSEL_SEARCH><TMPL_INCLUDE NAME="inputs_fields/fcra_search.tpl"></TMPL_IF>
<TMPL_IF NAME=LICENSE_SEARCH><TMPL_INCLUDE NAME="inputs_fields/license_search.tpl"></TMPL_IF>
<TMPL_IF NAME=PROF_LICENSE_SEARCH><TMPL_INCLUDE NAME="inputs_fields/prof_license_search.tpl"></TMPL_IF>
<TMPL_IF NAME=DL_REG_SEARCH><TMPL_INCLUDE NAME="inputs_fields/dl_reg_search.tpl"></TMPL_IF>
<TMPL_IF NAME=FAA_PILOT_SEARCH><TMPL_INCLUDE NAME="inputs_fields/faa_pilot_search.tpl"></TMPL_IF>
<TMPL_IF NAME=FCRA_FAA_PILOT_SEARCH><TMPL_INCLUDE NAME="inputs_fields/fcra_search.tpl"></TMPL_IF>
<TMPL_IF NAME=LIEN_SEARCH><TMPL_INCLUDE NAME="inputs_fields/lien_search.tpl"></TMPL_IF>
<TMPL_IF NAME=FCRA_LIENS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/fcra_search.tpl"></TMPL_IF>
<TMPL_IF NAME=BANKRUPTCY_SEARCH><TMPL_INCLUDE NAME="inputs_fields/bankruptcy_search.tpl"></TMPL_IF>
<TMPL_IF NAME=FCRA_BANKRUPTCY_SEARCH><TMPL_INCLUDE NAME="inputs_fields/fcra_search.tpl"></TMPL_IF>
<TMPL_IF NAME=BLJ_SEARCH><TMPL_INCLUDE NAME="inputs_fields/blj_search.tpl"></TMPL_IF>
<TMPL_IF NAME=FCRA_BLJ_SEARCH><TMPL_INCLUDE NAME="inputs_fields/blj_search.tpl"></TMPL_IF>
<TMPL_IF NAME=SEXPREDATOR_SEARCH><TMPL_INCLUDE NAME="inputs_fields/sexpredator_search.tpl"></TMPL_IF>
<TMPL_IF NAME=FCRA_SEXPREDATOR_SEARCH><TMPL_INCLUDE NAME="inputs_fields/fcra_search.tpl"></TMPL_IF>
<TMPL_IF NAME=OFFICIAL_RECORDS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/official_records_search.tpl"></TMPL_IF>
<TMPL_IF NAME=MARRIAGE_SEARCH><TMPL_INCLUDE NAME="inputs_fields/marriage_search.tpl"></TMPL_IF>
<TMPL_IF NAME=FCRA_MARRIAGE_SEARCH><TMPL_INCLUDE NAME="inputs_fields/fcra_search.tpl"></TMPL_IF>
<TMPL_IF NAME=FORECLOSURE_SEARCH><TMPL_INCLUDE NAME="inputs_fields/foreclosure_search.tpl"></TMPL_IF>
<TMPL_IF NAME=DEA_SEARCH><TMPL_INCLUDE NAME="inputs_fields/dea_search.tpl"></TMPL_IF>
<TMPL_IF NAME=ACCIDENT_SEARCH><TMPL_INCLUDE NAME="inputs_fields/accident_search.tpl"></TMPL_IF>
<TMPL_IF NAME=MVR_REPORT><TMPL_INCLUDE NAME="inputs_fields/mvr_report.tpl"></TMPL_IF>
<TMPL_IF NAME=CRIM_SEARCH><TMPL_INCLUDE NAME="inputs_fields/crim_search.tpl"></TMPL_IF>
<TMPL_IF NAME=FCRA_CRIM_SEARCH><TMPL_INCLUDE NAME="inputs_fields/fcra_search.tpl"></TMPL_IF>
<TMPL_IF NAME=PATRIOTACT_SEARCH><TMPL_INCLUDE NAME="inputs_fields/patriotact_search.tpl"></TMPL_IF>
<TMPL_IF NAME=CIVIL_COURT_SEARCH><TMPL_INCLUDE NAME="inputs_fields/civil_court_search.tpl"></TMPL_IF>
<TMPL_IF NAME=HUNTING_LICENSE_SEARCH><TMPL_INCLUDE NAME="inputs_fields/hunting_license_search.tpl"></TMPL_IF>
<TMPL_IF NAME=FCRA_HUNTING_LICENSE_SEARCH><TMPL_INCLUDE NAME="inputs_fields/fcra_search.tpl"></TMPL_IF>
<TMPL_IF NAME=CONCEALED_WEAPON_SEARCH><TMPL_INCLUDE NAME="inputs_fields/concealed_weapon_search.tpl"></TMPL_IF>
<TMPL_IF NAME=FCRA_CONCEALED_WEAPON_SEARCH><TMPL_INCLUDE NAME="inputs_fields/fcra_search.tpl"></TMPL_IF>
<TMPL_IF NAME=VOTER_REGISTRATION_SEARCH><TMPL_INCLUDE NAME="inputs_fields/voter_registration_search.tpl"></TMPL_IF>
<TMPL_IF NAME=FIREARMS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/firearms_search.tpl"></TMPL_IF>
<TMPL_IF NAME=FCRA_FIREARMS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/fcra_search.tpl"></TMPL_IF>
<TMPL_IF NAME=PERSON_SEARCH><TMPL_INCLUDE NAME="inputs_fields/person_search.tpl"></TMPL_IF>
<TMPL_IF NAME=FAP_SEARCH><TMPL_INCLUDE NAME="inputs_fields/person_search.tpl"></TMPL_IF>
<TMPL_IF NAME=PAW_SEARCH><TMPL_INCLUDE NAME="inputs_fields/paw_search.tpl"></TMPL_IF>
<TMPL_IF NAME=INSTANT_ID_REPORT><TMPL_INCLUDE NAME="inputs_fields/instant_id_report.tpl"></TMPL_IF>
<TMPL_IF NAME=SHOW_INTL_INSTANTID><TMPL_INCLUDE NAME="inputs_fields/intl_instantid_search.tpl"></TMPL_IF>
<TMPL_IF NAME=BUS_INSTANT_ID_REPORT><TMPL_INCLUDE NAME="inputs_fields/bus_instant_id_report.tpl"></TMPL_IF>
<TMPL_IF NAME=RATE_EVASION_REPORT><TMPL_INCLUDE NAME="inputs_fields/rate_evasion_report.tpl"></TMPL_IF>
<TMPL_IF NAME=NEWS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/news_search.tpl"></TMPL_IF>
<TMPL_IF NAME=NEG_NEWS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/neg_news_search.tpl"></TMPL_IF>
<TMPL_IF NAME=ADV_SEARCH><TMPL_INCLUDE NAME="inputs_fields/adv_search.tpl"></TMPL_IF>
<TMPL_IF NAME=PERSON_SEARCH_PLUS><TMPL_INCLUDE NAME="inputs_fields/adv_search.tpl"></TMPL_IF>
<TMPL_IF NAME=DA_BASIC_SEARCH><TMPL_INCLUDE NAME="inputs_fields/da_basic_search.tpl"></TMPL_IF>
<TMPL_IF NAME=DA_REVERSE_SEARCH><TMPL_INCLUDE NAME="inputs_fields/da_reverse_search.tpl"></TMPL_IF>
<TMPL_IF NAME=PHONE_IDENTIFIER_SEARCH><TMPL_INCLUDE NAME="inputs_fields/phone_identifier_search.tpl"></TMPL_IF>
<TMPL_IF NAME=DA_WIRELESS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/da_wireless_search.tpl"></TMPL_IF>
<TMPL_IF NAME=LOCATE_PLUS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/locate_plus_search.tpl"></TMPL_IF>
<TMPL_IF NAME=TODAYS_NEWS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/todays_news_search.tpl"></TMPL_IF>
<TMPL_IF NAME=US_NEWS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/us_news_search.tpl"></TMPL_IF>
<TMPL_IF NAME=NON_US_NEWS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/us_news_search.tpl"></TMPL_IF>
<TMPL_IF NAME=ARCHIVED_NEWS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/us_news_search.tpl"></TMPL_IF>
<TMPL_IF NAME=FED_CIVIL_COURT_SEARCH><TMPL_INCLUDE NAME="inputs_fields/fed_civil_court_search.tpl"></TMPL_IF>
<TMPL_IF NAME=FED_CRIM_COURT_SEARCH><TMPL_INCLUDE NAME="inputs_fields/fed_civil_court_search.tpl"></TMPL_IF>
<TMPL_IF NAME=PSPR_SEARCH><TMPL_INCLUDE NAME="inputs_fields/pspr_search.tpl"></TMPL_IF>
<TMPL_IF NAME=DO_NEWS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/do_news_search.tpl"></TMPL_IF>
<TMPL_IF NAME=OSHA_SEARCH><TMPL_INCLUDE NAME="inputs_fields/osha_search.tpl"></TMPL_IF>
<TMPL_IF NAME=DBGLOBAL_SEARCH><TMPL_INCLUDE NAME="inputs_fields/dbglobal_search.tpl"></TMPL_IF>
<TMPL_IF NAME=INSTOPICS_NEWS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/instopic_news_search.tpl"></TMPL_IF>
<TMPL_IF NAME=OABMS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/oabms_search.tpl"></TMPL_IF>
<TMPL_IF NAME=MP_PROVIDERS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/mp_providers_search.tpl"></TMPL_IF>
<TMPL_IF NAME=MP_SPECIALITIES_SEARCH><TMPL_INCLUDE NAME="inputs_fields/mp_specialities_search.tpl"></TMPL_IF>
<TMPL_IF NAME=MP_HOSPITALS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/mp_hospitals_search.tpl"></TMPL_IF>
<TMPL_IF NAME=COURT_CASE_SEARCH><TMPL_INCLUDE NAME="inputs_fields/court_case_search_by_type_search.tpl"></TMPL_IF>
<TMPL_IF NAME=PROVIDER_SEARCH><TMPL_INCLUDE NAME="inputs_fields/provider_search.tpl"></TMPL_IF>
<TMPL_IF NAME=SANCTION_SEARCH><TMPL_INCLUDE NAME="inputs_fields/sanction_search.tpl"></TMPL_IF>
<TMPL_IF NAME=CARFAX_REPORT><TMPL_INCLUDE NAME="inputs_fields/carfax_report.tpl"></TMPL_IF>
<TMPL_IF NAME=DEATH_SEARCH><TMPL_INCLUDE NAME="inputs_fields/death_search.tpl"></TMPL_IF>
<TMPL_IF NAME=CANADIAN_PHONES_SEARCH><TMPL_INCLUDE NAME="inputs_fields/canadian_phones_search.tpl"></TMPL_IF>
<TMPL_IF NAME=PRUDENTIAL_REPORT><TMPL_INCLUDE NAME="inputs_fields/prudential_report.tpl"></TMPL_IF>
<TMPL_IF NAME=EMAIL_SEARCH><TMPL_INCLUDE NAME="inputs_fields/email_search.tpl"></TMPL_IF>
<TMPL_IF NAME=CLAIMS_DISCOVERY_REPORT><TMPL_INCLUDE NAME="inputs_fields/claims_discovery_report.tpl"></TMPL_IF>
<TMPL_IF NAME=FEIN_SEARCH><TMPL_INCLUDE NAME="inputs_fields/fein_search.tpl"></TMPL_IF>
<TMPL_IF NAME=RT_MVR_SEARCH><TMPL_INCLUDE NAME="inputs_fields/rt_mvr_search.tpl"></TMPL_IF>
<TMPL_IF NAME=RT_PHONE_SEARCH><TMPL_INCLUDE NAME="inputs_fields/rt_phone_search.tpl"></TMPL_IF>
<TMPL_IF NAME=CARRIER_DISCOVERY_REPORT><TMPL_INCLUDE NAME="inputs_fields/carrier_discovery_report.tpl"></TMPL_IF>
<TMPL_IF NAME=REAL_PROPERTY_SEARCH><TMPL_INCLUDE NAME="inputs_fields/real_property_search.tpl"></TMPL_IF>
<TMPL_IF NAME=FCRA_REAL_PROPERTY_SEARCH><TMPL_INCLUDE NAME="inputs_fields/fcra_real_property_search.tpl"></TMPL_IF>
<TMPL_IF NAME=PERSON_DTR_REPORT><TMPL_INCLUDE NAME="inputs_fields/direct_to_report.tpl"></TMPL_IF>
<TMPL_IF NAME=POWER_BOOLEAN_SEARCH><TMPL_INCLUDE NAME="inputs_fields/power_boolean_search.tpl"></TMPL_IF>
<TMPL_IF NAME=MV_WILDCARD_SEARCH><TMPL_INCLUDE NAME="inputs_fields/mv_wildcard_search.tpl"></TMPL_IF>
<TMPL_IF NAME=POLICE_RECORDS_AUTO_ACCIDENT_SEARCH><TMPL_INCLUDE NAME="inputs_fields/police_records_auto_accident_search.tpl"></TMPL_IF>
<TMPL_IF NAME=POLICE_RECORDS_ALL_VEHICLES_SEARCH><TMPL_INCLUDE NAME="inputs_fields/police_records_all_vehicles_search.tpl"></TMPL_IF>
<TMPL_IF NAME=POLICE_RECORDS_ARREST_RECORD_SEARCH><TMPL_INCLUDE NAME="inputs_fields/police_records_arrest_record_search.tpl"></TMPL_IF>
<TMPL_IF NAME=POLICE_RECORDS_AUTOPSY_SEARCH><TMPL_INCLUDE NAME="inputs_fields/police_records_autopsy_search.tpl"></TMPL_IF>
<TMPL_IF NAME=POLICE_RECORDS_AUTO_THEFT_SEARCH><TMPL_INCLUDE NAME="inputs_fields/police_records_auto_theft_search.tpl"></TMPL_IF>
<TMPL_IF NAME=POLICE_RECORDS_AUTO_THEFT_RECOVERY_SEARCH><TMPL_INCLUDE NAME="inputs_fields/police_records_auto_theft_recovery_search.tpl"></TMPL_IF>
<TMPL_IF NAME=POLICE_RECORDS_BIRTH_CERTIFICATE_SEARCH><TMPL_INCLUDE NAME="inputs_fields/police_records_birth_certificate_search.tpl"></TMPL_IF>
<TMPL_IF NAME=POLICE_RECORDS_CITATION_SEARCH><TMPL_INCLUDE NAME="inputs_fields/police_records_citation_search.tpl"></TMPL_IF>
<TMPL_IF NAME=POLICE_RECORDS_DEATH_CERTIFICATE_SEARCH><TMPL_INCLUDE NAME="inputs_fields/police_records_death_certificate_search.tpl"></TMPL_IF>
<TMPL_IF NAME=POLICE_RECORDS_DUI_SEARCH><TMPL_INCLUDE NAME="inputs_fields/police_records_dui_search.tpl"></TMPL_IF>
<TMPL_IF NAME=POLICE_RECORDS_EMS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/police_records_ems_search.tpl"></TMPL_IF>
<TMPL_IF NAME=POLICE_RECORDS_FACE_SHEET_SEARCH><TMPL_INCLUDE NAME="inputs_fields/police_records_face_sheet_search.tpl"></TMPL_IF>
<TMPL_IF NAME=POLICE_RECORDS_FIRE_BLDG_SEARCH><TMPL_INCLUDE NAME="inputs_fields/police_records_fire_bldg_search.tpl"></TMPL_IF>
<TMPL_IF NAME=POLICE_RECORDS_FIRE_CAR_SEARCH><TMPL_INCLUDE NAME="inputs_fields/police_records_fire_car_search.tpl"></TMPL_IF>
<TMPL_IF NAME=POLICE_RECORDS_HOMICIDE_SEARCH><TMPL_INCLUDE NAME="inputs_fields/police_records_homicide_search.tpl"></TMPL_IF>
<TMPL_IF NAME=POLICE_RECORDS_INS_VERIFY_SEARCH><TMPL_INCLUDE NAME="inputs_fields/police_records_ins_verify_search.tpl"></TMPL_IF>
<TMPL_IF NAME=POLICE_RECORDS_ISSUE_LETTER_SEARCH><TMPL_INCLUDE NAME="inputs_fields/police_records_issue_letter_search.tpl"></TMPL_IF>
<TMPL_IF NAME=POLICE_RECORDS_OTHER_SEARCH><TMPL_INCLUDE NAME="inputs_fields/police_records_other_search.tpl"></TMPL_IF>
<TMPL_IF NAME=POLICE_RECORDS_PHOTOS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/police_records_photos_search.tpl"></TMPL_IF>
<TMPL_IF NAME=POLICE_RECORDS_RECONSTRUCTION_SEARCH><TMPL_INCLUDE NAME="inputs_fields/police_records_reconstruction_search.tpl"></TMPL_IF>
<TMPL_IF NAME=POLICE_RECORDS_REGISTERED_VEHICLE_SEARCH><TMPL_INCLUDE NAME="inputs_fields/police_records_registered_vehicle_search.tpl"></TMPL_IF>
<TMPL_IF NAME=POLICE_RECORDS_SUPPLEMENTAL_SEARCH><TMPL_INCLUDE NAME="inputs_fields/police_records_supplemental_search.tpl"></TMPL_IF>
<TMPL_IF NAME=POLICE_RECORDS_BURGLARY_SEARCH><TMPL_INCLUDE NAME="inputs_fields/police_records_burglary_search.tpl"></TMPL_IF>
<TMPL_IF NAME=POLICE_RECORDS_TITLE_HISTORY_SEARCH><TMPL_INCLUDE NAME="inputs_fields/police_records_title_history_search.tpl"></TMPL_IF>
<TMPL_IF NAME=POLICE_RECORDS_TOXICOLOGY_SEARCH><TMPL_INCLUDE NAME="inputs_fields/police_records_toxicology_search.tpl"></TMPL_IF>
<TMPL_IF NAME=POLICE_RECORDS_VANDALISM_SEARCH><TMPL_INCLUDE NAME="inputs_fields/police_records_vandalism_search.tpl"></TMPL_IF>
<TMPL_IF NAME=BUS_QUALIFIER_REPORT><TMPL_INCLUDE NAME="inputs_fields/bus_qualifier_report.tpl"></TMPL_IF>
<TMPL_IF NAME=IND_QUALIFIER_REPORT><TMPL_INCLUDE NAME="inputs_fields/ind_qualifier_report.tpl"></TMPL_IF>
<TMPL_IF NAME=REAL_TIME_PERSON_SEARCH><TMPL_INCLUDE NAME="inputs_fields/real_time_person_search.tpl"></TMPL_IF>
<TMPL_IF NAME=SOC_REPORT><TMPL_INCLUDE NAME="inputs_fields/soc_search.tpl"></TMPL_IF>
<TMPL_IF NAME=VIRTUAL_ID_SEARCH><TMPL_INCLUDE NAME="inputs_fields/virtual_identity_search.tpl"></TMPL_IF>
<TMPL_IF NAME=JAILBOOKING_SEARCH><TMPL_INCLUDE NAME="inputs_fields/jailbooking_search.tpl"></TMPL_IF>
<TMPL_IF NAME=CARRIER_ID_REPORT><TMPL_INCLUDE NAME="inputs_fields/carrier_id_report.tpl"></TMPL_IF>
<TMPL_IF NAME=WORKPLACE_SEARCH><TMPL_INCLUDE NAME="inputs_fields/workplace_search.tpl"></TMPL_IF>
<TMPL_IF NAME=DDESKTOP_SEARCH><TMPL_INCLUDE NAME="inputs_fields/dynamic_desktop_search.tpl"></TMPL_IF>
<TMPL_IF NAME=COMPSEARCH_SEARCH><TMPL_INCLUDE NAME="inputs_fields/comp_search.tpl"></TMPL_IF>
<TMPL_IF NAME=INTDOCKETS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/intdockets_search.tpl"></TMPL_IF>
<TMPL_IF NAME=INTPROFLIC_SEARCH><TMPL_INCLUDE NAME="inputs_fields/intproflic_search.tpl"></TMPL_IF>
<TMPL_IF CONTACT_PLUS_SEARCH><TMPL_INCLUDE inputs_fields/contact_search.tpl></TMPL_IF>
<TMPL_IF NAME=NPI_SEARCH><TMPL_INCLUDE NAME="inputs_fields/npi_data_search.tpl"></TMPL_IF>
<TMPL_IF NAME=PASSPORT_SEARCH><TMPL_INCLUDE NAME="inputs_fields/passport_validation.tpl"></TMPL_IF>
<TMPL_IF NAME=CLIA_SEARCH><TMPL_INCLUDE NAME="inputs_fields/clia_search.tpl"></TMPL_IF>
<TMPL_IF NAME=FIRST_PURSUIT><TMPL_INCLUDE NAME="inputs_fields/first_pursuit.tpl"></TMPL_IF>
<TMPL_IF NAME=NCPDP_SEARCH><TMPL_INCLUDE NAME="inputs_fields/ncpdp_search.tpl"></TMPL_IF>
<TMPL_IF NAME=SOCIALMEDIA_SEARCH><TMPL_INCLUDE NAME="inputs_fields/socialmedia_search.tpl"></TMPL_IF>
<TMPL_IF NAME=DISCLOSED_ENTITY_REPORT><TMPL_INCLUDE NAME="inputs_fields/disclosed_entity_report.tpl"></TMPL_IF>
<TMPL_IF NAME=PROVIDER_REPORT_CARD><TMPL_INCLUDE NAME="inputs_fields/provider_report_card.tpl"></TMPL_IF>
<TMPL_UNLESS HIDE_CASE_CONNECT_OPT_IN>
  <TMPL_IF SHOW_CC_OPTIN>
    <TMPL_INCLUDE case_connect/opt_in_block.tpl>
  </TMPL_IF>
</TMPL_UNLESS>
<TMPL_IF NAME=ID_VERIFY><TMPL_INCLUDE NAME="inputs_fields/id_verification.tpl"></TMPL_IF>
<TMPL_IF NAME=SHOW_PREMISES><TMPL_INCLUDE NAME="inputs_fields/premises_report.tpl"></TMPL_IF>
<TMPL_IF NAME=TRENDREPORTS><TMPL_INCLUDE NAME="inputs_fields/trendreports_options.tpl"></TMPL_IF>
<TMPL_IF NAME=COURTTRUSTEE><TMPL_INCLUDE NAME="inputs_fields/courttrustee_options.tpl"></TMPL_IF>
<TMPL_IF NAME=FILEAREA><TMPL_INCLUDE NAME="inputs_fields/filearea_options.tpl"></TMPL_IF>
<TMPL_IF NAME=FCRA_BK_EVENTS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/bk_events_search.tpl"></TMPL_IF>
<TMPL_IF NAME=FCRA_BK_COURT_LINKS_SEARCH><TMPL_INCLUDE NAME="inputs_fields/fcra_search.tpl"></TMPL_IF>
<!-- end inputs_fields/search_inputs_fields.tpl -->

<TMPL_INCLUDE NAME="zip_city_auto_complete.tpl">
