
1. License.  Seisint hereby grants to Customer a non-exclusive license (the "License") to use the Software solely in conjunction with its use of the Accurint Services and solely in connection with the acceptable uses identified by Customer in its Accurint Application and Agreement.  At all times Seisint shall maintain its ownership of, and all rights, title and interest in the Software as initially provided or subsequently modified under this contract or otherwise.  No title to, or ownership of, the Software shall be transferred to Customer by way of the granting of this License.  Customer shall not create derivative works of, reverse assemble, reverse engineer, reverse compile or otherwise reduce to human readable form the Software without Seisint's prior written consent.
 
2. Restrictions of Government Rights.  If the Customer is a federal Government entity that employs  Federal Acquisition Regulations wherein the Government may be entitled to limited government rights, including but not limited to FARS 48 CFR Sec. 52.227-13, 52.227-14, and 52.227-15 in its contracts, then it is specifically agreed by the Customer that rights conferred to the Government by such regulations shall be restricted in accordance with the terms and conditions of this License unless the development of a new deliverable or the substantial and material augmentation of a prior  deliverable has been (a) directly funded by the Government, and (b) has not previously been made commercially available by Seisint.

3. Warranties.  Seisint shall license the Software to Customer "as is."  Seisint will not warrant that the Software is fit for a particular purpose, or that the Software is of merchantable quality, and Seisint will disclaim all other warranties regarding the Software of any kind, whether actual or implied; provided, however, Seisint will warrant that (a) it owns and has the right to license the Software to Customer, (b) the Software does not infringe upon the intellectual property rights of any third party, (c) in licensing the Software  to Customer, Seisint is not violating the intellectual property rights of any third party, and (d) the Software is unencumbered by any adverse claims, liens, security interests, or judgments that would inhibit in any way Customer's possession, use and enjoyment of the Software.  

4. Disclosure of Software.  Customer may engage, with Seisint's reasonable consent, third party contractors/service providers to provide outsourced services with respect to the Software.  Customer shall limit access to the Software to only such employees or third party contractors/service providers engaged by Customer having a "need to know", and Customer shall treat the Software as being "For Official Use Only (FOUO)" to protect the Software  from disclosure. Government Customers hereby specifically acknowledge and agree that the Software contains Trade Secrets as defined in the Trade Secrets Act, 18 U.S.C. §1905, and exemption 4 of the Freedom of Information Act, 5 U.S.C. §552 (b)(4).  

5. Term.  The term of this Agreement shall run concurrent with the term of that certain Accurint Application and Agreement entered into between Customer and Seisint.  The Customer agrees that if Seisint finds Customer to be in material violation of this Agreement, Seisint shall have the right to terminate this Agreement. 

6. Seisint Audit Rights.  Customer agrees that Seisint shall have the right to audit and monitor Customer's processes and procedures (observing in the case of Government Customers all pertinent requirements concerning the treatment of classified information) and to directly and through its independent auditors, upon at least three (3) business day's prior written notice, to visit Customer's facilities during normal business hours.  Seisint, or its designee, may inspect Customer's facilities and records (including electronic records necessary to ascertaining compliance) and interview Customer's employees or third party contractors/service providers to ensure that Customer is in compliance with the terms and conditions of the license; provided, however, such audits shall be reasonable in number and scope, and shall not become an impediment to Customer's quiet enjoyment of the Software.  Except as required by law, Seisint agrees to maintain the confidentiality of all of Customer's procedures, processes and all other information that are disclosed to it as a result of the audit.  If an audit reveals a violation of the License Seisint agrees to promptly notify Customer in writing of any problems discovered and to allow Customer two (2) business days to cure the problem.  If Customer is unable to cure a breach of this License, or otherwise make Seisint whole relative to a breach, then such notification shall not in any manner act as a waiver by Seisint of such rights.

7. Assignment.  Customer shall not be entitled to assign, sell or transfer the rights to this License without Seisint's express written consent. 

8. Special Circumstances.  If the Customer is a federal Government entity using the Software for purposes related to national defense or anti-terrorism, then notwithstanding the terms and conditions of Section 1 of this License, due to (a) Times of War (b) threats to National Security or (c) actual or threatened terrorist acts (the "Special Circumstances"), if the Contracting Officer for the federal Government entity determines in writing it is imperative to immediately modify or enhance the Software to address such a Special Circumstance, then for purposes of the modification or enhancement Seisint shall immediately make available to the federal Government entity personnel (i) appropriate and available developers and programmers who in Seisint's opinion have the skills necessary to work with the Federal Government entity's personnel to allow prompt delivery of the requested modification or enhancement, and (ii) the source code to the Software   at a secure site located at Seisint's facilities for purposes of Seisint personnel performing the requested modification or enhancement.  Upon the request of Seisint the Customer shall pay Seisint the commercial rate for the programming and development personnel assigned.  Seisint shall own all right, title and interest in and to, including distribution rights, the code, concepts, designs and other intellectual property developed as a result of a modification or enhancement made under Special Circumstances.

9. Limitation of Liability.  Seisint shall not be liable to Customer for any incidental, indirect, exemplary, special, or consequential damages, under any circumstances, including, but not limited to, breach of contract, tort, or strict liability, even if Seisint had been advised of, knew, or should have known, of the possibility thereof.   

10. Export Law Assurances.   The Customer may not use or otherwise export or re-export the Software except as authorized by United States law.  In particular, but without limitation, the Software  may not be exported or re-exported (i) into (or to a national or resident or) any U.S. embargoed county or (ii) to anyone on the U.S. Treasury Department's list of Specially Designated Nationals or the U.S. Department of Commerce's Table of Denial Orders.  

11. Controlling Law and Severability.  This License shall be governed and construed by the laws of the United States and the State of Florida.  If for any reason a court of competent jurisdiction finds any provision, or portion thereof, to be unenforceable, the remainder of this License shall continue in full force and effect.

12. Complete Agreement.  This License constitutes the entire agreement between the Parties with respect to the use of the Software and supersedes all prior or contemporaneous understandings regarding such subject matter.  No amendment to or modification of this License will be binding unless in writing and signed by an authorized representative of Seisint.

13. Indemnification. Customer shall indemnify and hold harmless Seisint from and against any and all suits, claims or damages incurred by Seisint arising from or in connection with any claims of injury to person or property as connected to the use of the Software by the Customer.
