Login ID, Name, Date Added, Last Login Date, Admin, Suspended
<TMPL_LOOP NAME=USER_LIST><TMPL_VAR NAME=LOGINID>,<TMPL_VAR NAME=FIRSTNAME> <TMPL_VAR NAME=LASTNAME>,<TMPL_VAR NAME=DATEADDED>,<TMPL_VAR NAME=LAST_LOGIN_DATE>,<TMPL_VAR NAME=SYSTEMADMINISTRATOR_DISPLAY>,<TMPL_VAR NAME=SUSPENDED_DISPLAY>
</TMPL_LOOP>
