<!-- BEGIN v3/batch/people/append_bus_fields_body.tpl -->
<div class="fieldset-title">Select the fields you wish to have appended to your file</div>			  
<table>
    <tr>
        <td class="batchsubheader">
            Basic Business Batch -- <TMPL_UNLESS HIDE_PRICES>$.25 for basic </TMPL_UNLESS>data plus any of the following
        </td>
    </tr>
    <tr>
        <td><input type="checkbox" name="includebusphone" value="1" <TMPL_VAR NAME=includebusphone> onClick="if(!checkallow_bus(this)){return false;};">Other Businesses at Phone&nbsp;&nbsp;<a href="javascript:void(0);" onClick="var layerfgcolor = get_layer_colors('fgcolor');var layerbgcolor = get_layer_colors('bgcolor');return overlib_to_modal('<br>Append up to six (6) other businesses associated with the phone number in the basic batch result.<br><br>', CAPTIONSIZE, 2, BORDER, 3, FGCOLOR, layerfgcolor, BGCOLOR, layerbgcolor, CGCOLOR, layerbgcolor, WIDTH, 275, FIXX, 250, FIXY, 205, STICKY, CAPTION, 'Other Busniesses at Phone', CLOSECLICK, CLOSETEXT, '<img border=0 width=16 height=16 alt=\'Close\' title=\'Close\' src=\'<TMPL_VAR NAME=IMGPATH>/closex.gif\'>');"><img src="<TMPL_VAR NAME=IMGPATH>/info.gif" border="0" width="16" height="16"></a></td>
    </tr>
    <tr>
        <td><input type="checkbox" name="includebusaddress" value="1" <TMPL_VAR NAME=includebusaddress> onClick="if(!checkallow_bus(this)){return false;};">Other Businesses at Address&nbsp;&nbsp;<a href="javascript:void(0);" onClick="var layerfgcolor = get_layer_colors('fgcolor');var layerbgcolor = get_layer_colors('bgcolor');return overlib_to_modal('<br>Appends up to ten (10) other businesses associated with the address in the basic batch result.<br><br>', CAPTIONSIZE, 2, BORDER, 3, FGCOLOR, layerfgcolor, BGCOLOR, layerbgcolor, CGCOLOR, layerbgcolor, WIDTH, 275, FIXX, 250, FIXY, 205, STICKY, CAPTION, 'Other Busniesses at Address', CLOSECLICK, CLOSETEXT, '<img border=0 width=16 height=16 alt=\'Close\' title=\'Close\' src=\'<TMPL_VAR NAME=IMGPATH>/closex.gif\'>');"><img src="<TMPL_VAR NAME=IMGPATH>/info.gif" border="0" width="16" height="16"></a></td>
    </tr>
    <tr>
        <td>&nbsp;<b>Add any of the following:</b></td>
    </tr>
    <tr>
        <td><input type="checkbox" name="includebusbankruptcy" value="1" <TMPL_VAR NAME=includebusbankruptcy> onClick="if(!checkallow_bus(this)){return false;};change_total(this, <TMPL_VAR NAME=includebusbankruptcy-price>,document.forms[0].BATCH_TOTAL,document.forms[0].BATCH_PRE_TOTAL)">Add a Current Bankruptcy<TMPL_UNLESS HIDE_PRICES> for only an additional $0.25 per record submitted</TMPL_UNLESS>&nbsp;&nbsp;<a href="javascript:void(0);" onClick="var layerfgcolor = get_layer_colors('fgcolor');var layerbgcolor = get_layer_colors('bgcolor');return overlib_to_modal('<br>Appends the most recent bankruptcy data matching the (1) company and state or (2) just the company name.  NOTE: The company name and address may not be identical matches to the basic batch result.<br><br>', CAPTIONSIZE, 2, BORDER, 3, FGCOLOR, layerfgcolor, BGCOLOR, layerbgcolor, CGCOLOR, layerbgcolor, WIDTH, 275, FIXX, 230, FIXY, 205, STICKY, CAPTION, 'Current Bankruptcies', CLOSECLICK, CLOSETEXT, '<img border=0 width=16 height=16 alt=\'Close\' title=\'Close\' src=\'<TMPL_VAR NAME=IMGPATH>/closex.gif\'>');"><img src="<TMPL_VAR NAME=IMGPATH>/info.gif" border="0" width="16" height="16"></a></td>
    </tr>
    <tr>
        <td><input type="checkbox" name="includecorpfilings" value="1" <TMPL_VAR NAME=includecorpfilings> onClick="if(!checkallow_bus(this)){return false;};change_total(this, <TMPL_VAR NAME=includecorpfilings-price>,document.forms[0].BATCH_TOTAL,document.forms[0].BATCH_PRE_TOTAL)">Add Current Corporate Filing<TMPL_UNLESS HIDE_PRICES> for only $1.00 per record match</TMPL_UNLESS>&nbsp;&nbsp;<a href="javascript:void(0);" onClick="var layerfgcolor = get_layer_colors('fgcolor');var layerbgcolor = get_layer_colors('bgcolor');return overlib_to_modal('<br>Appends one corporate filing record, matching the (1) company and state or (2) just the company name.  NOTE: The company name and address may not be identical matches to the basic batch result.<br><br>', CAPTIONSIZE, 2, BORDER, 3, FGCOLOR, layerfgcolor, BGCOLOR, layerbgcolor, CGCOLOR, layerbgcolor, WIDTH, 275, FIXX, 230, FIXY, 205, STICKY, CAPTION, 'Current Corporate Filings', CLOSECLICK, CLOSETEXT, '<img border=0 width=16 height=16 alt=\'Close\' title=\'Close\' src=\'<TMPL_VAR NAME=IMGPATH>/closex.gif\'>');"><img src="<TMPL_VAR NAME=IMGPATH>/info.gif" border="0" width="16" height="16"></a></td>
    </tr>
    <tr>
        <td>&nbsp;<b>OR select a Preconfigured Append:</b></td>
    </tr>
    <tr>
        <td><input type="checkbox" name="busreversephones" value="1" <TMPL_VAR NAME=busreversephones> onClick="clearcorpfilingsonly(<TMPL_VAR NAME=corpfilingsonly-price>);clearbuscorp(<TMPL_VAR NAME=includecorpfilings-price>);clearbusbankruptcy(<TMPL_VAR NAME=includebusbankruptcy-price>);change_total(this, <TMPL_VAR NAME=busreversephones-price>,document.forms[0].BATCH_TOTAL,document.forms[0].BATCH_PRE_TOTAL);quickpick_bus(this);">Reverse Phone Lookup<TMPL_UNLESS HIDE_PRICES> for $.10 per record match</TMPL_UNLESS>&nbsp;&nbsp;<a href="javascript:void(0);" onClick="var layerfgcolor = get_layer_colors('fgcolor');var layerbgcolor = get_layer_colors('bgcolor');return overlib_to_modal('<br>Appends to the output record name and address based on the submitted phone number.<br><br>', CAPTIONSIZE, 2, BORDER, 3, FGCOLOR, layerfgcolor, BGCOLOR, layerbgcolor, CGCOLOR, layerbgcolor, WIDTH, 275, FIXX, 330, FIXY, 320, STICKY, CAPTION, 'Reverse Phone Lookups', CLOSECLICK, CLOSETEXT, '<img border=0 width=16 height=16 alt=\'Close\' title=\'Close\' src=\'<TMPL_VAR NAME=IMGPATH>/closex.gif\'>');"><img src="<TMPL_VAR NAME=IMGPATH>/info.gif" border="0" width="16" height="16"></a></td>
    </tr>
    <tr>
        <td><input type="checkbox" name="corpfilingsonly" value="1" <TMPL_VAR NAME=corpfilingsonly> onClick="clearbusreversephones(<TMPL_VAR NAME=busreversephones-price>);clearbuscorp(<TMPL_VAR NAME=includecorpfilings-price>);clearbusbankruptcy(<TMPL_VAR NAME=includebusbankruptcy-price>);change_total(this, <TMPL_VAR NAME=corpfilingsonly-price>,document.forms[0].BATCH_TOTAL,document.forms[0].BATCH_PRE_TOTAL);quickpick_bus(this);">Corporate Filings<TMPL_UNLESS HIDE_PRICES> for $1.00 per record match</TMPL_UNLESS>&nbsp;&nbsp;<a href="javascript:void(0);" onClick="var layerfgcolor = get_layer_colors('fgcolor');var layerbgcolor = get_layer_colors('bgcolor');return overlib_to_modal('<br>Appends up to six (6) records sorted by filing date in reverse chronological order. The order of precedence for matching is (1) company name and address; (2) company and state then (3) company name only.<br><br>', CAPTIONSIZE, 2, BORDER, 3, FGCOLOR, layerfgcolor, BGCOLOR, layerbgcolor, CGCOLOR, layerbgcolor, WIDTH, 275, FIXX, 330, FIXY, 320, STICKY, CAPTION, 'Corporate Filings', CLOSECLICK, CLOSETEXT, '<img border=0 width=16 height=16 alt=\'Close\' title=\'Close\' src=\'<TMPL_VAR NAME=IMGPATH>/closex.gif\'>');"><img src="<TMPL_VAR NAME=IMGPATH>/info.gif" border="0" width="16" height="16"></a></td>
    </tr>
</table>
<!-- END v3/batch/people/append_bus_fields_body.tpl -->