<!-- Begin exempt_user_msg.tpl -->
<font face="verdana" size="3" color="red"><b>ALTHOUGH YOUR ACCURINT ACCOUNT HAS AN EXEMPT STATUS, PLACING THIS COURT SEARCH ORDER WILL RESULT IN YOUR CREDIT CARD BEING CHARGED.  IF YOU DO NOT WANT YOUR CREDIT CARD CHARGED DO NOT PROCEED WITH THIS ORDER.  ALL COURT SEARCH ORDERS ARE FINAL AND NON-REFUNDABLE.</b>
</font>
<!-- End exempt_user_msg.tpl -->
