<form name="BILLING_ACTIVITY" action="<TMPL_VAR NAME=ACTION_ADMIN>" method="post">
      <TMPL_INCLUDE NAME="common_hidden_input.tpl">
      <INPUT type=hidden NAME="EVENT" VALUE="BILLING/ACTIVITY">

<INPUT TYPE=hidden NAME="BILLING_LOGIN_FILTER" VALUE="">

<INPUT TYPE="HIDDEN" NAME="NEXT_PAGE_DATE" VALUE="<TMPL_VAR NAME=NEXT_PAGE_DATE>">
<INPUT TYPE="HIDDEN" NAME="PREV_PAGE_DATE" VALUE="<TMPL_VAR NAME=PREV_PAGE_DATE>">
<INPUT TYPE="HIDDEN" NAME="PAGE_COUNT" VALUE="<TMPL_VAR NAME=PAGE_COUNT>">
<INPUT TYPE="HIDDEN" NAME="PAGE_TOTAL" VALUE="<TMPL_VAR NAME=PAGE_TOTAL>">
<INPUT TYPE="HIDDEN" NAME="PAGE_RECORDS" VALUE="<TMPL_VAR NAME=PAGE_RECORDS>">
<TMPL_IF NAME="HAS_FCRA_NON_FCRA">
<INPUT TYPE="HIDDEN" NAME="FCRA_CURRENT_NEXT_PAGE_DATE" VALUE="<TMPL_VAR NAME=FCRA_CURRENT_NEXT_PAGE_DATE>">
<INPUT TYPE="HIDDEN" NAME="FCRA_CURRENT_PREV_PAGE_DATE" VALUE="<TMPL_VAR NAME=FCRA_CURRENT_PREV_PAGE_DATE>">
<INPUT TYPE="HIDDEN" NAME="FCRA_NEXT_PAGE_DATE" VALUE="<TMPL_VAR NAME=FCRA_NEXT_PAGE_DATE>">
<INPUT TYPE="HIDDEN" NAME="FCRA_PREV_PAGE_DATE" VALUE="<TMPL_VAR NAME=FCRA_PREV_PAGE_DATE>">
<INPUT TYPE="HIDDEN" NAME="PAGE_COUNT_FCRA" VALUE="<TMPL_VAR NAME=PAGE_COUNT_FCRA>">
<INPUT TYPE="HIDDEN" NAME="PAGE_TOTAL_FCRA" VALUE="<TMPL_VAR NAME=PAGE_TOTAL_FCRA>">
<INPUT TYPE="HIDDEN" NAME="PAGE_RECORDS_FCRA" VALUE="<TMPL_VAR NAME=PAGE_RECORDS_FCRA>">
<input type="hidden" name="FCRA_BILLING_DATE_TO" value="<TMPL_VAR NAME=FCRA_BILLING_DATE_TO>">
<input type="hidden" name="FCRA_BILLING_DATE_FROM" value="<TMPL_VAR NAME=FCRA_BILLING_DATE_FROM>">
<INPUT TYPE="HIDDEN" NAME="CURRENT_NEXT_PAGE_DATE" VALUE="<TMPL_VAR NAME=CURRENT_NEXT_PAGE_DATE>">
<INPUT TYPE="HIDDEN" NAME="CURRENT_PREV_PAGE_DATE" VALUE="<TMPL_VAR NAME=CURRENT_PREV_PAGE_DATE>">
<INPUT TYPE="HIDDEN" NAME="CURRENT_DIRECTION" VALUE="<TMPL_VAR NAME=CURRENT_DIRECTION>">
<INPUT TYPE="HIDDEN" NAME="FCRA_CURRENT_DIRECTION" VALUE="<TMPL_VAR NAME=FCRA_CURRENT_DIRECTION>">
</TMPL_IF>
<INPUT TYPE="HIDDEN" NAME="PAGE_LOGINID" VALUE="<TMPL_VAR NAME=PAGE_LOGINID>">
<input type="hidden" name="BILLING_DATE_TO" value="<TMPL_VAR NAME=BILLING_DATE_TO>">
<input type="hidden" name="BILLING_DATE_FROM" value="<TMPL_VAR NAME=BILLING_DATE_FROM>">
<INPUT TYPE=hidden NAME="tz" VALUE="">
</form>
